# Generated by Django 5.2.3 on 2025-06-22 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientprofile',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
